# Run a set of tests, each in its own container and with a potentially customized setup.

# To this end, each test is launched via docker_container_driver.sh, part of the single-node
# test harness machinery whose implementation and documentation is to be found in the
# `irods/test/harness` directory.

# A test may be written as a Bash or BATS script, but the only real requirement is that it be
# executable.

name: run-test-programs-single-node

on: [push, pull_request]

jobs:
  tests:
    name: Python ${{ matrix.python }}, iRODS ${{ matrix.irods_server }}
    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: ./test_harness/single_node
    strategy:
      matrix:
        python: ['3.9','3.13']
        irods_server: ['4.3.4','5.0.2']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build images
        run: ./create_docker_images.sh "${{ matrix.irods_server }}" "${{ matrix.python }}"

      - name: run tests
        run: |
          for script in \
              ../../irods/test/scripts/test[0-9]* \
              ../../irods/test/login_auth_test_*.py
          do
              ./docker_container_driver.sh -V $script
          done
